services:
  projetcine:
    build: .
    container_name: projetcine
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      PROJETCINE_DATA: /app/data
    networks:
      - nginx-proxy-manager_default
networks:
  nginx-proxy-manager_default:
    external: true
